name: cs5670_python_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - opencv
  - pillow
  - py-opencv
  - pyparsing=2.4.7
  - python
  - pyttk=0.3.2
  - scipy
  - tk=8.6.10


